Repository jitsi/lib-jitsi-meet, pull requests merged in 2020-10, with the labels that each got.

#1349 e2ee: sync key ring size and packet format
  doc/e2ee.md
  modules/e2ee/Context.js
Labels: feature-request

#1353 feat(RTC): force cursor of ScreenObtainer to be always captured
  modules/RTC/ScreenObtainer.js
Labels: browser-support

#1350 feat(xmpp) drop the useStunTurn option
  doc/API.md
  modules/xmpp/strophe.jingle.js
  modules/xmpp/xmpp.js
Labels: feature-request

#1354 Add missing options to docs and improve naming
  README.md
  doc/API.md
Labels: bug

#1373 (feat) e2ee: sign and verify frames
  doc/e2ee.md
  modules/e2ee/Context.js
  modules/e2ee/Context.spec.js
  modules/e2ee/E2EEContext.js
  modules/e2ee/E2EEncryption.js
  modules/e2ee/Worker.js
Labels: feature-request
