Repository jitsi/lib-jitsi-meet, pull requests merged in 2021-08, with the labels that each got.

#1672 feat: enable config callstats configParams
  JitsiConference.js
  modules/statistics/CallStats.js
  modules/statistics/statistics.js
Labels: feature-request

#1685 Workaround for Chrome ice connection failure detection
  modules/RTC/TraceablePeerConnection.js
  modules/xmpp/JingleSessionPC.js
Labels: bug, browser-support

#1698 fix(replace-track) Add not null check for newTrack
  JitsiConference.js
Labels: bug
